service: D_ProjectName_D

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  randomNumber:
    handler: dist/lambdas/RandomNumber.handle
    events:
      - http:
          path: /random-number
          method: get
