service: D_ProjectName_D

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_REGION}

functions:
  server:
    handler: dist/index.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
