version: '3.7'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    ports:
      - 5432:5432

  D_entity_D-service:
    image: node:11
    volumes:
      - ./:/usr/src/service
    ports:
      - 9229:9229
      - 3200:3200
    depends_on:
      - postgres
    command: bash -c "yarn dev"
    working_dir: /usr/src/service
    environment:
      - PORT=3200
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password